### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sdspieg** [pdrm83/sent2vec#2]
Trying to install it from anaconda on Windows 10 with python 3, I get the following error
`    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\sdspi\similarity\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sdspi\\AppData\\Local\\Temp\\pip-install-n83rq8q8\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\sdspi\\AppData\\Local\\Temp\\pip-install-n83rq8q8\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sdspi\AppData\Local\Temp\pip-record-53kxjmpx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\sdspi\similarity\include\site\python3.7\torch'
         cwd: C:\Users\sdspi\AppData\Local\Temp\pip-install-n83rq8q8\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sdspi\AppData\Local\Temp\pip-install-n83rq8q8\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "c:\users\sdspi\similarity\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\sdspi\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\sdspi\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\sdspi\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sdspi\AppData\Local\Temp\pip-install-n83rq8q8\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\sdspi\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\sdspi\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sdspi\AppData\Local\Temp\pip-install-n83rq8q8\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\sdspi\similarity\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sdspi\\AppData\\Local\\Temp\\pip-install-n83rq8q8\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\sdspi\\AppData\\Local\\Temp\\pip-install-n83rq8q8\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sdspi\AppData\Local\Temp\pip-record-53kxjmpx\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\sdspi\similarity\include\site\python3.7\torch' Check the logs for full command output.`

**Comment by pdrm83** [comment]
Sorry to get back to you late. Please feel free to contribute and revise. I would be appreciated if you can help improve this open-source project.
